### ISSUE TITLE
Code won't compile on CloudPebble.

### ISSUE THREAD

**Issue by Snowflake6** [jrmobley/horizon-watchface#1]
Here is a copy of the build log when I try to build on CloudPebble.  It seems to get stuck when the code tries to require the module "raw".

Setting top to                           : /tmp/tmpLKKHMc 
Setting out to                           : /tmp/tmpLKKHMc/build 
Checking for program webpack             : /app/node_modules/.bin/webpack 
Found Pebble SDK for emery in:           : /app/sdk3/pebble/emery 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for diorite in:         : /app/sdk3/pebble/diorite 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for chalk in:           : /app/sdk3/pebble/chalk 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for basalt in:          : /app/sdk3/pebble/basalt 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for aplite in:          : /app/sdk3/pebble/aplite 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
'configure' finished successfully (0.191s)
Waf: Entering directory `/tmp/tmpLKKHMc/build'
[  2/100] message_key_header:  -> build/include/message_keys.auto.h
[  3/100] message_key_definitions:  -> build/src/message_keys.auto.c
[  3/100] message_key_json:  -> build/js/message_keys.json
[  7/100] emery | appinfo.auto.c:  -> build/emery/appinfo.auto.c
[  7/100] emery | subst: ../../app/sdk3/pebble/common/pebble_app.ld.template -> build/emery/pebble_app.ld.auto
[  6/100] emery | appinfo.json:  -> build/appinfo.json
[  7/100] emery | reso: resources/images/icon.png -> build/emery/resources/images/icon.png.MENU_ICON.reso
[  8/100] emery | reso: resources/data/din-condensed.ffont -> build/emery/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso
[  9/100] emery | c: build/src/message_keys.auto.c -> build/src/message_keys.auto.c.37.o
[ 10/100] emery | resource_ball: build/emery/resources/images/icon.png.MENU_ICON.reso build/emery/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso -> build/emery/system_resources.resball
[ 13/100] emery | generate_pbpack: build/emery/system_resources.resball -> build/emery/app_resources.pbpack
[ 13/100] emery | generate_resource_id_header: build/emery/system_resources.resball -> build/emery/src/resource_ids.auto.h
[ 13/100] emery | generate_resource_id_definitions: build/emery/system_resources.resball -> build/emery/src/resource_ids.auto.c
[ 14/100] emery | c: build/emery/src/resource_ids.auto.c -> build/emery/src/resource_ids.auto.c.37.o
[ 15/100] emery | c: build/emery/appinfo.auto.c -> build/emery/appinfo.auto.c.37.o
[ 16/100] emery | c: src/c/sysfont.c -> build/src/c/sysfont.c.37.o
[ 17/100] emery | c: src/c/main.c -> build/src/c/main.c.37.o
[ 18/100] emery | c: src/c/isqrt.c -> build/src/c/isqrt.c.37.o
[ 19/100] emery | cprogram: build/src/c/isqrt.c.37.o build/src/c/main.c.37.o build/src/c/sysfont.c.37.o build/emery/appinfo.auto.c.37.o build/emery/src/resource_ids.auto.c.37.o build/src/message_keys.auto.c.37.o -> build/emery/pebble-app.elf
[ 20/100] emery | memory_usage_report: build/emery/pebble-app.elf build/emery/app_resources.pbpack
-------------------------------------------------------
EMERY APP MEMORY USAGE
Total size of resources:        10400 bytes / 256KB
Total footprint in RAM:         9352 bytes / 128KB
Free RAM available (heap):      121720 bytes
------------------------------------------------------- 
[ 24/100] diorite | subst: ../../app/sdk3/pebble/common/pebble_app.ld.template -> build/diorite/pebble_app.ld.auto
[ 24/100] diorite | appinfo.auto.c:  -> build/diorite/appinfo.auto.c
[ 25/100] diorite | reso: resources/images/icon.png -> build/diorite/resources/images/icon.png.MENU_ICON.reso
[ 25/100] diorite | reso: resources/data/din-condensed.ffont -> build/diorite/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso
[ 26/100] diorite | c: build/src/message_keys.auto.c -> build/src/message_keys.auto.c.38.o
[ 27/100] diorite | resource_ball: build/diorite/resources/images/icon.png.MENU_ICON.reso build/diorite/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso -> build/diorite/system_resources.resball
[ 28/100] diorite | generate_resource_id_definitions: build/diorite/system_resources.resball -> build/diorite/src/resource_ids.auto.c
[ 29/100] diorite | generate_pbpack: build/diorite/system_resources.resball -> build/diorite/app_resources.pbpack
[ 30/100] diorite | generate_resource_id_header: build/diorite/system_resources.resball -> build/diorite/src/resource_ids.auto.h
[ 31/100] diorite | c: src/c/main.c -> build/src/c/main.c.38.o
[ 32/100] diorite | c: src/c/sysfont.c -> build/src/c/sysfont.c.38.o
[ 33/100] diorite | c: src/c/isqrt.c -> build/src/c/isqrt.c.38.o
[ 34/100] diorite | c: build/diorite/appinfo.auto.c -> build/diorite/appinfo.auto.c.38.o
[ 35/100] diorite | c: build/diorite/src/resource_ids.auto.c -> build/diorite/src/resource_ids.auto.c.38.o
[ 36/100] diorite | cprogram: build/src/c/isqrt.c.38.o build/src/c/main.c.38.o build/src/c/sysfont.c.38.o build/diorite/appinfo.auto.c.38.o build/diorite/src/resource_ids.auto.c.38.o build/src/message_keys.auto.c.38.o -> build/diorite/pebble-app.elf
[ 37/100] diorite | memory_usage_report: build/diorite/pebble-app.elf build/diorite/app_resources.pbpack
-------------------------------------------------------
DIORITE APP MEMORY USAGE
Total size of resources:        10269 bytes / 256KB
Total footprint in RAM:         9672 bytes / 64KB
Free RAM available (heap):      55864 bytes
------------------------------------------------------- 
[ 39/100] chalk | subst: ../../app/sdk3/pebble/common/pebble_app.ld.template -> build/chalk/pebble_app.ld.auto
[ 40/100] chalk | appinfo.auto.c:  -> build/chalk/appinfo.auto.c
[ 41/100] chalk | reso: resources/images/icon.png -> build/chalk/resources/images/icon.png.MENU_ICON.reso
[ 42/100] chalk | reso: resources/data/din-condensed.ffont -> build/chalk/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso
[ 43/100] chalk | c: build/src/message_keys.auto.c -> build/src/message_keys.auto.c.39.o
[ 44/100] chalk | resource_ball: build/chalk/resources/images/icon.png.MENU_ICON.reso build/chalk/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso -> build/chalk/system_resources.resball
[ 46/100] chalk | generate_pbpack: build/chalk/system_resources.resball -> build/chalk/app_resources.pbpack
[ 47/100] chalk | generate_resource_id_definitions: build/chalk/system_resources.resball -> build/chalk/src/resource_ids.auto.c
[ 47/100] chalk | generate_resource_id_header: build/chalk/system_resources.resball -> build/chalk/src/resource_ids.auto.h
[ 48/100] chalk | c: build/chalk/src/resource_ids.auto.c -> build/chalk/src/resource_ids.auto.c.39.o
[ 49/100] chalk | c: src/c/isqrt.c -> build/src/c/isqrt.c.39.o
[ 50/100] chalk | c: src/c/sysfont.c -> build/src/c/sysfont.c.39.o
[ 51/100] chalk | c: build/chalk/appinfo.auto.c -> build/chalk/appinfo.auto.c.39.o
[ 52/100] chalk | c: src/c/main.c -> build/src/c/main.c.39.o
[ 53/100] chalk | cprogram: build/src/c/isqrt.c.39.o build/src/c/main.c.39.o build/src/c/sysfont.c.39.o build/chalk/appinfo.auto.c.39.o build/chalk/src/resource_ids.auto.c.39.o build/src/message_keys.auto.c.39.o -> build/chalk/pebble-app.elf
[ 54/100] chalk | memory_usage_report: build/chalk/pebble-app.elf build/chalk/app_resources.pbpack
-------------------------------------------------------
CHALK APP MEMORY USAGE
Total size of resources:        10400 bytes / 256KB
Total footprint in RAM:         9356 bytes / 64KB
Free RAM available (heap):      56180 bytes
------------------------------------------------------- 
[ 57/100] basalt | subst: ../../app/sdk3/pebble/common/pebble_app.ld.template -> build/basalt/pebble_app.ld.auto
[ 57/100] basalt | appinfo.auto.c:  -> build/basalt/appinfo.auto.c
[ 58/100] basalt | reso: resources/images/icon.png -> build/basalt/resources/images/icon.png.MENU_ICON.reso
[ 59/100] basalt | reso: resources/data/din-condensed.ffont -> build/basalt/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso
[ 60/100] basalt | c: build/src/message_keys.auto.c -> build/src/message_keys.auto.c.40.o
[ 61/100] basalt | resource_ball: build/basalt/resources/images/icon.png.MENU_ICON.reso build/basalt/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso -> build/basalt/system_resources.resball
[ 62/100] basalt | generate_pbpack: build/basalt/system_resources.resball -> build/basalt/app_resources.pbpack
[ 64/100] basalt | generate_resource_id_definitions: build/basalt/system_resources.resball -> build/basalt/src/resource_ids.auto.c
[ 64/100] basalt | generate_resource_id_header: build/basalt/system_resources.resball -> build/basalt/src/resource_ids.auto.h
[ 65/100] basalt | c: build/basalt/src/resource_ids.auto.c -> build/basalt/src/resource_ids.auto.c.40.o
[ 66/100] basalt | c: src/c/main.c -> build/src/c/main.c.40.o
[ 67/100] basalt | c: build/basalt/appinfo.auto.c -> build/basalt/appinfo.auto.c.40.o
[ 68/100] basalt | c: src/c/sysfont.c -> build/src/c/sysfont.c.40.o
[ 69/100] basalt | c: src/c/isqrt.c -> build/src/c/isqrt.c.40.o
[ 70/100] basalt | cprogram: build/src/c/isqrt.c.40.o build/src/c/main.c.40.o build/src/c/sysfont.c.40.o build/basalt/appinfo.auto.c.40.o build/basalt/src/resource_ids.auto.c.40.o build/src/message_keys.auto.c.40.o -> build/basalt/pebble-app.elf
[ 71/100] basalt | memory_usage_report: build/basalt/pebble-app.elf build/basalt/app_resources.pbpack
-------------------------------------------------------
BASALT APP MEMORY USAGE
Total size of resources:        10400 bytes / 256KB
Total footprint in RAM:         9352 bytes / 64KB
Free RAM available (heap):      56184 bytes
------------------------------------------------------- 
[ 75/100] aplite | subst: ../../app/sdk3/pebble/common/pebble_app.ld.template -> build/aplite/pebble_app.ld.auto
[ 75/100] aplite | reso: resources/images/icon.png -> build/aplite/resources/images/icon.png.MENU_ICON.reso
[ 75/100] aplite | appinfo.auto.c:  -> build/aplite/appinfo.auto.c
[ 76/100] aplite | reso: resources/data/din-condensed.ffont -> build/aplite/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso
[ 77/100] aplite | c: build/src/message_keys.auto.c -> build/src/message_keys.auto.c.41.o
[ 78/100] aplite | resource_ball: build/aplite/resources/images/icon.png.MENU_ICON.reso build/aplite/resources/data/din-condensed.ffont.DIN_CONDENSED_FFONT.reso -> build/aplite/system_resources.resball
[ 80/100] aplite | generate_resource_id_header: build/aplite/system_resources.resball -> build/aplite/src/resource_ids.auto.h
[ 80/100] aplite | generate_pbpack: build/aplite/system_resources.resball -> build/aplite/app_resources.pbpack
[ 81/100] aplite | generate_resource_id_definitions: build/aplite/system_resources.resball -> build/aplite/src/resource_ids.auto.c
[ 82/100] aplite | c: build/aplite/src/resource_ids.auto.c -> build/aplite/src/resource_ids.auto.c.41.o
[ 83/100] aplite | c: src/c/main.c -> build/src/c/main.c.41.o
[ 84/100] aplite | c: src/c/sysfont.c -> build/src/c/sysfont.c.41.o
[ 85/100] aplite | c: build/aplite/appinfo.auto.c -> build/aplite/appinfo.auto.c.41.o
[ 86/100] aplite | c: src/c/isqrt.c -> build/src/c/isqrt.c.41.o
[ 87/100] aplite | cprogram: build/src/c/isqrt.c.41.o build/src/c/main.c.41.o build/src/c/sysfont.c.41.o build/aplite/appinfo.auto.c.41.o build/aplite/src/resource_ids.auto.c.41.o build/src/message_keys.auto.c.41.o -> build/aplite/pebble-app.elf
[ 88/100] aplite | memory_usage_report: build/aplite/pebble-app.elf build/aplite/app_resources.pbpack
-------------------------------------------------------
APLITE APP MEMORY USAGE
Total size of resources:        10269 bytes / 128KB
Total footprint in RAM:         9672 bytes / 24KB
Free RAM available (heap):      14904 bytes
------------------------------------------------------- 
[ 90/100] emery | pebble-app.raw.bin: build/emery/pebble-app.elf -> build/emery/pebble-app.raw.bin
[ 90/100] aplite | merge_js: src/pkjs/app.js src/pkjs/colors.js src/pkjs/config.js src/pkjs/custom-clay.js src/pkjs/sunriset.js -> build/pebble-js-app.js
[ 91/100] diorite | pebble-app.raw.bin: build/diorite/pebble-app.elf -> build/diorite/pebble-app.raw.bin
[ 92/100] chalk | pebble-app.raw.bin: build/chalk/pebble-app.elf -> build/chalk/pebble-app.raw.bin
[ 93/100] basalt | pebble-app.raw.bin: build/basalt/pebble-app.elf -> build/basalt/pebble-app.raw.bin
[ 94/100] aplite | pebble-app.raw.bin: build/aplite/pebble-app.elf -> build/aplite/pebble-app.raw.bin
[ 95/100] emery | inject-metadata: build/emery/pebble-app.raw.bin build/emery/pebble-app.elf build/emery/app_resources.pbpack -> build/emery/pebble-app.bin
[ 98/100] basalt | inject-metadata: build/basalt/pebble-app.raw.bin build/basalt/pebble-app.elf build/basalt/app_resources.pbpack -> build/basalt/pebble-app.bin
[ 98/100] diorite | inject-metadata: build/diorite/pebble-app.raw.bin build/diorite/pebble-app.elf build/diorite/app_resources.pbpack -> build/diorite/pebble-app.bin
[ 98/100] aplite | inject-metadata: build/aplite/pebble-app.raw.bin build/aplite/pebble-app.elf build/aplite/app_resources.pbpack -> build/aplite/pebble-app.bin
[ 99/100] chalk | inject-metadata: build/chalk/pebble-app.raw.bin build/chalk/pebble-app.elf build/chalk/app_resources.pbpack -> build/chalk/pebble-app.bin
Waf: Leaving directory `/tmp/tmpLKKHMc/build'
Build failed
Traceback (most recent call last):
  File "/app/sdk3/pebble/.waf-1.7.11-1c991d94a43fe16c569124a366b5ad58/waflib/Task.py", line 123, in process
    ret=self.run()
  File "/app/sdk3/pebble/.waf-1.7.11-1c991d94a43fe16c569124a366b5ad58/waflib/Task.py", line 47, in run
    return m1(self)
  File "/app/sdk3/pebble/.waf-1.7.11-1c991d94a43fe16c569124a366b5ad58/waflib/extras/process_js.py", line 121, in run
    bld.fatal("JS bundling failed\n{}\n{}".format(e.stdout,e.stderr))
  File "/app/sdk3/pebble/.waf-1.7.11-1c991d94a43fe16c569124a366b5ad58/waflib/Context.py", line 219, in fatal
    raise self.errors.ConfigurationError(msg,ex=ex)
ConfigurationError: JS bundling failed
Hash: 0993d93a1861fa3cd66a
Version: webpack 1.13.2
Time: 428ms
           Asset    Size  Chunks             Chunk Names
pebble-js-app.js  226 kB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
   [1] /app/sdk3/pebble/common/include/_pkjs_shared_additions.js 195 bytes {0} [built]
   [2] ./src/pkjs/app.js 7.61 kB {0} [built] [2 errors]
   [3] ./~/underscore/underscore.js 52.9 kB {0} [built]
   [4] ./src/pkjs/sunriset.js 12.9 kB {0} [built]
   [5] ./src/pkjs/colors.js 3.04 kB {0} [built]
   [6] ./build/js/message_keys.json 275 bytes {0} [built]
   [7] ./~/pebble-clay/dist/js/index.js 126 kB {0} [built]
   [8] /app/sdk3/pebble/common/include/_message_key_wrapper.js 179 bytes {0} [built]
   [9] ./src/pkjs/config.js 8.09 kB {0} [built]
  [10] ./src/pkjs/custom-clay.js 5.41 kB {0} [built]
  [11] ./~/pebble-clay-preview-component/dist/js/index.js 4.12 kB {0} [built]

WARNING in ./~/pebble-clay/dist/js/index.js
Critical dependencies:
2:418-425 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/pebble-clay/dist/js/index.js 2:418-425

ERROR in ./src/pkjs/app.js
Module not found: Error: Cannot resolve module 'raw' in /tmp/tmpLKKHMc/src/pkjs
 @ ./src/pkjs/app.js 22:35-63

ERROR in ./src/pkjs/app.js
Module not found: Error: Cannot resolve module 'raw' in /tmp/tmpLKKHMc/src/pkjs
 @ ./src/pkjs/app.js 22:65-93

**Comment by jrmobley** [comment]
Satisfying the raw-loader dependency isn't enough.  I'll have to move some files around too, so that cloudpebble can find them.

**Comment by jrmobley** [comment]
Well, some kludgy business was required, but the project should be cloudpebble compatible now.

**Comment by Snowflake6** [comment]
Awesome, thanks!  I'll go try it now.

**Comment by Snowflake6** [comment]
Sorry, forgot to come back and update.  I can confirm that compile is now successful on CloudPebble, and it runs on all platforms.  Side benefit:  I discovered that there is a settings page for this app that I hadn't seen before!  Awesome!  :)
